spring:
  application:
    name: lifestream
  data:
    mongodb:
      uri: mongodb://localhost:27017/lifestream
      database: lifestream

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
